### ISSUE TITLE
Prefix search for table name is not working as expected for some table

### ISSUE THREAD

**Issue by shimpeko** [hogelog/dmemo#74]
For example, searching with the word "push" won't list "push_notification_token" table on the result, although other tables like "push_notification_settings" is listed.

I'm not sure about the patterns of table name which will be listed with prefix search or not.

Note: Searching with full table name (not prefix) is working expectedly.

My version is 0.4.0-rc.

**Comment by hogelog** [comment]
Table search feature is implemented before version 0.1.4.
I will maintain searching.

**Comment by hogelog** [comment]
Before #78, there is search result number limitation.
Currently search results contains all tables and columns.
