### ISSUE TITLE
Database column is always active.

### ISSUE THREAD

**Issue by CM-Kajiwara** [hogelog/dmemo#75]
I moved Keyword contents ,but Database column is active in sidemenu.
I use dmemo version 0.3.2.

左側のサイドメニューの項目が、
他のページ(Keyword等)に遷移しても必ずDatabaseがアクティブになっています。
Databaseが登録されたない状態のみかとも思ったのですが、
Databaseを登録しても同様の現象です。

**Comment by hogelog** [comment]
これはデータベース以外の項目についてはサブメニューをつくるつもりがないので意図的にそうしています。

常にアクティブなことで困ること、嬉しくないことはありましたか？

**Comment by CM-Kajiwara** [comment]
![keyword](http://cdn.dev.classmethod.jp/wp-content/uploads/2016/09/dmemo_07.png)

上記の画像のように、
今現在ユーザーはKeywordのページに遷移してKeywordの項目を編集しているのに、
右側のカラムではDatabaseがActiveなので、自分がいるページはKeywordではなくDatabaseのページの項目を編集していると錯覚してしまったのでIssueとして記載しました。

**Comment by hogelog** [comment]
なるほどー、元々そういう用途で使うべきサブメニュー展開、アクティブ属性を意図を変えて使っちゃってるから使う人にに混乱をおこしちゃってる感じですね。
表示の調整なんかでいい感じにできないか検討します！

**Comment by hogelog** [comment]
![image](https://cloud.githubusercontent.com/assets/50920/18675268/cc800fc8-7f8c-11e6-89f2-b98387e7e5b4.png)
こんな感じでアクティブっぽさを排除してみました。
