### ISSUE TITLE
How to delete Keywords ?

### ISSUE THREAD

**Issue by CM-Kajiwara** [hogelog/dmemo#77]
一度登録したキーワードの削除は機能としてはないのでしょうか？

**Comment by hogelog** [comment]
お、実装忘れてたみたいですね。そのうちサクッと

**Comment by hogelog** [comment]
![image](https://cloud.githubusercontent.com/assets/50920/18675683/20624056-7f8e-11e6-81fe-12b3fd65e13b.png)
編集画面にサクッと。
42c4ef10376736558fc02e06e3618f9abb00d919
