### ISSUE TITLE
Update to Rails 5

### ISSUE THREAD

**Issue by naoki85** [hogelog/dmemo#98]
Hi, we use dmemo.  
Thanks a lot!!  

By the way, are you planning to update to Rails 5?

**Comment by hogelog** [comment]
Of course I'd like to do it, but I do not have a very high motivation now.

**Comment by snowhork** [comment]
We'll introduce dmemo to our team too, and develop some extension. Before that, we want upgrade to Rails 5.

If we post pull request for upgrading, can you review us (and merge)?

**Comment by hogelog** [comment]
I am looking forward your PR!

**Comment by hogelog** [comment]
@snowhork's #99 did it :tada:

**Comment by naoki85** [comment]
@snowhork Thanks a lot!!
